<a href="https://colab.research.google.com/github/harshdhiman-ai/PYPR/blob/main/PYPR_2021_EED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import tensorflow as tf
tf.test.gpu_device_name()

'/device:GPU:0'

In [ ]:
import math
math.trunc(62.6938)

62

In [ ]:
import numpy as np
import pandas as pd
x=np.array([[1,2,3],[4,5,6]]) # array x has two rows and three cols
print(x.shape)

(2, 3)


# Python Basics- Trigonometry

In [ ]:
import math
x=math.cos(math.pi/4)
print(x)

0.7071067811865476


In [ ]:
# Inverse Trignometric functions
print(math.asin(-1))

-1.5707963267948966


# Addition

#Data Types in Python

> Indented block

> Indented block





In [ ]:
# type() command is used for determining the type of a variable.
x=1
y=2.3
z='aha'
type(z)

str

In [ ]:
import math   # Python lib for math functions- log, exp, poly, hyperbolic
import cmath  # Python library for working with complex functions
# x=6+8i / 6+j8
num=complex(6,8) # x=3+j4
type(num)
abs_value=abs(num) # Magnitude of the complex number x+iy, sqrt(x^2+y^2)
print(y)
# Function name is abs(), argument will be ......


10.0
6.0


# Python Lists: Lists are used to store multiple items in a single variable.

Lists are one of 4 built-in data types in Python used to store collections of data

In [ ]:
x=[181,68.75,'harsh', 45.100007,'apple','indonesia']
# The most important/fundamental aspect is indexing 
# Indexing in python starts from 0
x[0] # Means the first element of your list
x[0:4] # This is known as list slicing
x[-1] # Points to the first element from the end, This is known as negative indexing of list
x[0]='Virat'
print(x)

['Virat', 68.75, 'harsh', 45.100007, 'apple', 'indonesia']


# Python Tuple: Tuples are used to store multiple items in a single variable.

Tuple is one of 4 built-in data types in Python used to store collections of data

In [ ]:
y=(1,2,4,'dell',64.08) # y is defined as a tuple. 
print(y)
## Tuples are ordered and unchangeble

(1, 2, 4, 'dell', 64.08)


# Python Sets: Sets are used to store multiple items in a single variable. Set is one of 4 built-in data types in Python used to store collections of data

In [ ]:
x={'apple','cherry','mango'}
# Set items are unordered and unchangeble
# Set cannot have duplicate values and will be ignored, For example
y={'apple','cherry','mango','apple'}
print(y)
#Set of voewls 
f={'a','e','i','o','u'}

{'cherry', 'apple', 'mango'}


TypeError: ignored

#Python Variables and Ops Lecture-3: 24/6/2021

In [ ]:
import cmath # Library to deal with complex number z=x+iy
import math # Log, exp, hyperbolic, sin, cos, trigno
#z=complex(3,4) # Aruguments are real and imag part of the CN , z= 3+j4
# Magnitude of a complex number |z|= sqrt(x^2+y^2)
#abs_z=abs(z)
# Task is 3 raised to 12 3^12 , 
# In Matlab, ^ known as carrot operator. 
# In C programming , pow(3,12): You have use #include <math.h>
a=1
b=2
c=a+b
print("The addition is",c)
# In C programming, printf("The addition is %d",c);
c=a-b
print("The sub is",c)
# Task is divide a by b and extract the remainder
c=a/b
print("The division is ",c)
c=a%b
print("The remainder is ",c)

The addition is 3
The sub is -1
The division is  0.5
The remainder is  1


# Python Arith Operations & Expressions

In [ ]:
a=1
b=2
import math
# Evaluate a^2+b^2-sqrt(a+b)
c=a**2+b**2-math.sqrt(a+b)
print("The expression is",c)
x=45
y=math.tan(math.pi/4) # angle pi/4
print(y)

The expression is 3.267949192431123
0.9999999999999999


#Python Relational & Logical Ops- (July 1, 2021)

In [ ]:
# Use of == operator
x=2
y=3.5
x==y
# Difference between = (Assignment) and ==(Relational operator)
#Strings in Python
x="python"
y="programming"
z=" "
print("The combined string is",x+z+y)

The combined string is python programming


In [ ]:
#Logical Operations in Python
# OR operator- symbol ||
import math
#OR operator (x+y), where x and y are binary inputs. False(0) and True(1)
#AND operator (x*y), where x and y are binary inputs. False(0) and True(1)
x=1
y=math.pi/6
theta=math.pi
#evaluate the expression
(x**2+math.sin(y))<(x-math.cos(theta)) and (math.sin(theta)+2*x < x*math.tan(y)) 

x*y #Normal multiplication
x**y # x raised to y

False

# A three-phase star-connected load draws a current 10∠ − 45◦ ampere. Assuming wires have negligible impedance, calculate active, reactive and apparent power if the system voltage is 400 Volts. Compare all the powers if the load current changes to 10∠45◦ ampere

In [ ]:
import math
import cmath
phi=float(input('enter phase angle'))
phi=phi*math.pi/180   ### degree to radian conversion for phase angle
I=float(input('enter current magnitude'))
V=float(input('enter line voltage'))
I_new=cmath.rect(I,phi)  ## cmath.rect converts polar to rectangular with arguments in form of mag and phase (in radians)
print(I_new)

enter phase angle0
enter current magnitude10
enter line voltage400
(10+0j)


In [ ]:
## Active Power: sqrt(3)*V_L*I_L*cos(phi)
act_power=math.sqrt(3)*V*I_new.real  
print("Active power in Watts is",act_power,'Watts')

## Reactive Power: sqrt(3)*V_L*I_L*sin(phi)
react_power=math.sqrt(3)*V*I_new.imag
print("Reactive power in VAR is",react_power,'VAR')

app_power=math.sqrt(3)*V*I_new   # S= sqrt(P^2+Q^2)
print("apparent power is ",app_power, 'VA')
#Absolute of Apparent power 
S=abs(app_power)
print("Magnitude of apparent power is",S,"VA")

Active power in Watts is 6928.203230275509 Watts
Reactive power in VAR is 0.0 VAR
apparent power is  (6928.203230275509+0j) VA
Magnitude of apparent power is 6928.203230275509 VA


# Square roots of Quadratic Eqn

In [ ]:
# x^2-8x+90=0 compare this equation with ax^2+bx+c=0
import math
import cmath
a=1
b=-8
c=90
D=cmath.sqrt(b**2-4*a*c)
# let us have two roots alpha and beta
alpha= (-b+D)/(2*a)
beta=(-b-D)/(2*a)
print("The roots are",alpha,beta)

The roots are (4+8.602325267042627j) (4-8.602325267042627j)


# Compare area of a square with that of circle

In [ ]:
a=5.12*0.01 # converison from cm to m
r=0.23  
area_s=a**2
import math
area_c=math.pi*r**2
area_c<area_s       # Initial Hypothesis: area of circle is less than area of sqaure

False

In [ ]:
x=1
y=0.94
v=3/math.pi
#import math
# Logical OR, if one input is HIGH, output is HIGH
(math.log(x**2)+9*math.exp(-y))>(7*v-math.log(x/4)) # log to the base e

# for example , e^(-x)
y=math.log2(2)
print(y)
x=1
y=2
import cmath
k=complex(3,4)
theta=36.86

math.log(x**2)-math.sin(theta*math.pi/180)+y**(4.4)-abs(k)/2.0

1.0


18.012264778524575

# Application of Electrical Engg in Python

In [ ]:
I=complex(60,80) # I=60+j80 ampere
V=complex(400,0) # Line-line voltage, V=400+j0 
# How will you find the p.f. ?
theta=math.atan(8/6)
theta=theta*(180/math.pi)
P=V*I.real
print("The active power is",P, "Watts")
Q=V*I.imag
print("The reactive power is",Q, "VAR")


80.0

# Numpy Module- Arrays in Python (July 8, 2021)



In [14]:
import numpy as np
import math 
a=np.array([1,2,5])  # create 1-D array
print(a)
x=np.array([[1,2,3],[4,5,6]]) # creates a 2-D array with 3 cols and 2 rows
print(x)
c=np.zeros(3) # creates 1-D array of length 3 with all zeros
print(c)
f=np.ones((5,2))  # creates 1-D array of size 5 x 2 with all ones
print(f)

[1 2 5]
[[1 2 3]
 [4 5 6]]
[0. 0. 0.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


# Additional numpy functions for arrays

In [19]:
x=np.eye(5) # 5 x 5 matrix with 1 as diagonal element and 0 as off-diagonal element 
print(x)
y=np.linspace(0,100,20) # creates array of 20 equally spaced elements b/w 0 and 100
print(y) 
z=np.arange(0,10,1) #Array of values from 0 to less than 10 with step 1
print(z) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
[0 1 2 3 4 5 6 7 8 9]


#Inspecting array properties

In [27]:
x=np.array([(1,2,3),(4,5,6)])
y=x.reshape((3,2))  # Changes the shape to 3x2 from 2x3
print(y)
y.shape # Matrix size in terms of rows and cols
x.size # Returns the number of elements in an array
p=x.tolist() # Converts array to a python list
print(p)
z=np.array([1,3,4,7,5,2,9])
w=np.sort(z) # Sorts a given array
print(w)

[[1 2]
 [3 4]
 [5 6]]
[[1, 2, 3], [4, 5, 6]]
[1 2 3 4 5 7 9]


# Indexing & Slicing in Arrays

In [29]:
x=np.array([1,2,3,4,5])
x[0:2]

array([1, 2])